### ISSUE TITLE
Input overflowed

### ISSUE THREAD

**Issue by HaroldPetersInskipp** [JoelShine/JARVIS-AI-ASSISTANT#6]
When running `python jarvis.py` it seems to respond okay for a moment then just continues rambling without further input and then overflows.
```
Loading from brain file: brain.dump
Loading brain from brain.dump...done (93208 categories in 1.55 seconds)
Listening
time
The time here is Mon Mar 20 17:46:12 2023
it's not
I heard    is.
i heard
That is interesting.
that is
Is that so.
isn't it
I really couldn't say for sure.
Traceback (most recent call last):
  File "C:\Users\Bannd\Downloads\TEMP\JARVIS-AI-ASSISTANT\jarvis.py", line 54, in <module>
    data = stream.read(4000)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pyaudio\__init__.py", line 570, in read
    return pa.read_stream(self._stream, num_frames,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno -9981] Input overflowed
```

EXTRA INFO: To get the assistant running I had to edit the file `C:\Python311\Lib\site-packages\aiml\Kernel.py` and replace all instances of `time.clock()` with `time.time()`.

**Comment by HaroldPetersInskipp** [comment]
I did not have issues installing pyaudio with the `pip install -r requirements.txt` command so I never ran `pip install PyAudio‑0.2.11‑cp38‑cp38‑win_amd64.whl`
Could that be the cause perhaps?
